# Base image with Node.js
FROM node:22.14.0

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy rest of the project files
COPY . .

# Expose JSON-RPC server
EXPOSE 8545

# Hardhat - compile contract
RUN npx hardhat compile
